version: '3.5'

services:
  el_kube:
    image: el_kube:latest
    container_name: el_kube
    env_file: docker.env
    depends_on:
      - db
    ports:
      - "4000:4000"

  db:
    image: postgres:9.6
    container_name: db
    environment:
      POSTGRES_DB: el_kube_dev
